Problems 2, 5, 12, 13, 14, 15, 17, 21

2. Consider the population {3, 6, 7, 9, 11, 14}. For samples of size 3 without replacement,
find (and plot) the sampling distribution of the minimum. What
is the mean of the sampling distribution? The statistic is an estimate of some
parameter—what is the value of that parameter?

```{r}
# Problem 2
```


5. Let X1,X2, . . . , Xn be a random sample from some distribution and suppose
Y = T (X1,X2, . . . , Xn) is a statistic. Suppose the sampling distribution of Y
has pdf f (y) = (3/8)y2 for 0 ≤ y ≤ 2. Find P(0 ≤ Y ≤ 1/5).

12. A friend claims that she has drawn a random sample of size 30 from the exponential
distribution with λ = 1/10. The mean of her sample is 12.

(a) What is the expected value of a sample mean?
(b) Run a simulation by drawing 1000 random samples, each of size 30, from
Exp(1/10) and then compute the mean. What proportion of the sample
means are as large as or larger than 12?
(c) Is a mean of 12 unusual for a sample of size 30 from Exp(1/10)?

13. Let X1,X2, . . .,X10
i.∼i.d. N(20, 82) and Y1, Y2, . . ., Y15
i.∼i.d. N(16, 72). Let
W = Xhat + Yhat.

(a) Give the exact sampling distribution of W.
(b) Simulate the sampling distribution in R and plot your results. Check that
the simulated mean and standard error are close to the theoretical mean and
the standard error.
(c) Use your simulation to find P(W < 40). Calculate an exact answer and
compare.

14. Let X1,X2, . . . , X9
i.∼i.d. N(7, 32) and Y1, Y2, . . . , Y12
i.∼i.d. N(10, 52). LetW = Xhat - Yhat.
(a) Give the exact sampling distribution of W.
(b) Simulate the sampling distribution of W in R and plot your results (adapt
code from the previous exercise). Check that the simulated mean and the
standard error are close to the theoretical mean and the standard error.
(c) Use your simulation to find P(W < −1.5). Calculate an exact answer and
compare.

15. Let X1,X2, . . . , Xn be a random sample from N(0, 1). Let W = X(1 to 2) + X(2 to 2) + ... + x(n to 2)

Describe the sampling distribution of W by running a simulation,
using n = 2. What is the mean and variance of the sampling distribution ofW?
Repeat using n = 4, n = 5. What observations or conjectures do you have for
general n?

17. Let X1,X2, . . . , X20 i.∼i.d. Exp(2). Let X = Sum from i = 1 to 20 Xsubi.

(a) Simulate the sampling distribution of X in R.
(b) From your simulation, find E [X] and Var[X].
(c) From your simulation, find P(X ≤ 10).

21. Let X1,X2 i.∼i.d. F with corresponding pdf f (x) = 2/x2, 1 ≤ x ≤ 2.
(a) Find the pdf of Xmax.
(b) Find the expected value of Xmax.

